/* BlueZone content engine. Loaded before main.js.
   Page data lives in js/pages-*.js and registers into BZ.pages / BZ.add / BZ.articles. */
(function(w){
var BZ=w.BZ=w.BZ||{};
BZ.pages=BZ.pages||{};BZ.add=BZ.add||{P:{},G:{}};BZ.articles=BZ.articles||[];
BZ.UPDATED='30 September 2026';BZ.ISO='2026-09-30';
function L(a){return '<ul>'+a.map(function(x){return '<li>'+x+'</li>'}).join('')+'</ul>'}
function T(h,rows,cap){return '<div class="tw"><table><thead><tr>'+h.map(function(x){return '<th>'+x+'</th>'}).join('')+'</tr></thead><tbody>'+rows.map(function(r){return '<tr>'+r.map(function(c){return '<td>'+c+'</td>'}).join('')+'</tr>'}).join('')+'</tbody></table></div>'+(cap?'<p class="src" style="margin-top:12px">'+cap+'</p>':'')}
function opts(a,sel){return a.map(function(o){var v=Array.isArray(o)?o[0]:o,t=Array.isArray(o)?o[1]:o;return '<option value="'+v+'"'+(String(v)===String(sel)?' selected':'')+'>'+t+'</option>'}).join('')}
function bands(){var a=[];for(var i=0;i<=18;i++)a.push((i/2).toFixed(1));return a.reverse()}
/* ---------- widgets ---------- */
var WG={
ielts:function(){var b=bands();return '<div class="card wg" data-wg="ielts"><h3>IELTS overall band calculator and target checker</h3><p>Enter your four section scores. The overall band is the average, rounded to the nearest half band, where .25 rounds up to the next half and .75 rounds up to the next whole band.</p><div class="cf4">'+[['l','Listening'],['r','Reading'],['w','Writing'],['s','Speaking']].map(function(x){return '<label>'+x[1]+'<select data-k="'+x[0]+'">'+opts(b,'6.0')+'</select></label>'}).join('')+'</div><div class="cf2"><label>Target overall band<select data-k="t">'+opts(b,'6.5')+'</select></label><label>Minimum required in every skill<select data-k="m">'+opts([['0','No minimum'],'5.0','5.5','6.0','6.5','7.0'],'5.5')+'</select></label></div><p class="out" data-o="res"></p><p class="out2" data-o="msg"></p></div>'},
plan:function(){var d=new Date(),o=[],m=[1,6,8,0];var y=d.getFullYear(),c=0;for(var yy=y;yy<=y+2&&c<8;yy++){[1,6,8,0].forEach(function(mm){var dt=new Date(yy,mm,1);if(dt>new Date(d.getFullYear(),d.getMonth()+3,1)&&c<8){o.push([dt.toISOString().slice(0,10),['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'][mm]+' '+yy+(mm==8?' (main intake)':mm==1||mm==6?' (Feb / Jul)':' (Jan)')]);c++}})}
o.sort(function(a,b){return a[0]<b[0]?-1:1});
return '<div class="card wg" data-wg="plan"><h3>Application timeline planner</h3><p>Pick your intake and destination. You get a dated checklist counted backwards from your start date. Steps already behind you are flagged so you can see what to compress.</p><div class="cf2"><label>Intake start<select data-k="d">'+opts(o,o[2]&&o[2][0])+'</select></label><label>Destination<select data-k="c">'+opts([['uk','United Kingdom'],['au','Australia'],['ca','Canada'],['us','United States'],['nz','New Zealand'],['ie','Ireland'],['my','Malaysia'],['cn','China']],'uk')+'</select></label></div><div data-o="res"></div></div>'},
funds:function(){return '<div class="card wg" data-wg="funds"><h3>First-year cash planner (visa funds + tuition)</h3><p>Uses the official living-cost funds figure for each country, then adds the tuition from your offer letter and the visa and health costs. Enter the exchange rate your bank quotes today, because rates move daily.</p><div class="cf4"><label>Destination<select data-k="c">'+opts([['uk','UK (GBP)'],['au','Australia (AUD)'],['ca','Canada (CAD)'],['nz','New Zealand (NZD)'],['ie','Ireland (EUR)']],'uk')+'</select></label><label>Tuition, first year (local currency)<input data-k="t" type="number" min="0" value="15000"></label><label>Health cover, per year (local currency)<input data-k="h" type="number" min="0" value="776"></label><label>Rate: PKR per 1 unit<input data-k="r" type="number" min="0" placeholder="e.g. your bank rate"></label></div><div class="cf2" data-o="extra"><label>Course length (years, for UK health surcharge)<input data-k="y" type="number" min="1" max="5" value="1"></label><label>UK only: study in London?<select data-k="lon"><option value="0">Outside London</option><option value="1">London</option></select></label></div><div data-o="res"></div></div>'},
emi:function(){return '<div class="card wg" data-wg="emi"><h3>Education loan repayment calculator</h3><p>Works for a bank loan or an interest-free Qarz-e-Hasna (enter 0 for the rate). Interest during your study period either gets added to the loan or is paid as you go.</p><div class="cf4"><label>Loan amount (PKR)<input data-k="p" type="number" min="0" value="6000000"></label><label>Annual rate (%)<input data-k="i" type="number" min="0" step="0.1" value="14"></label><label>Repayment years<input data-k="n" type="number" min="1" max="25" value="8"></label><label>Study period (months)<input data-k="g" type="number" min="0" max="72" value="12"></label></div><div class="cf2"><label>Interest during study<select data-k="cap"><option value="1">Added to the loan (capitalised)</option><option value="0">Paid monthly while studying</option></select></label><label>If the rupee weakens by (%) before you pay<select data-k="fx"><option value="0">0</option><option value="10">10</option><option value="20">20</option><option value="30">30</option></select></label></div><div data-o="res"></div></div>'},
pkr:function(){return '<div class="card wg" data-wg="pkr"><h3>How many rupees will this transfer cost?</h3><p>Enter the amount in foreign currency, your bank quote and its charges. This shows the real PKR cost, which is what goes on your bank statement and visa file.</p><div class="cf4"><label>Amount (foreign currency)<input data-k="a" type="number" min="0" value="10000"></label><label>Bank rate (PKR per unit)<input data-k="r" type="number" min="0" placeholder="bank quote"></label><label>Bank charge (% of amount)<input data-k="f" type="number" min="0" step="0.05" value="0"></label><label>Flat fees (PKR, SWIFT etc.)<input data-k="x" type="number" min="0" value="0"></label></div><div data-o="res"></div></div>'}
};
function g(c,k){var e=c.querySelector('[data-k="'+k+'"]');return e?e.value:''}
function o(c,n){return c.querySelector('[data-o="'+n+'"]')}
function nf(n){return Math.round(n).toLocaleString('en-US')}
var FD={uk:{cur:'£',per:[1171,1529],fee:558,note:'Living funds are counted for up to 9 months. Funds must be held for 28 consecutive days before you apply.'},au:{cur:'A$',fund:29710,fee:2500,note:'Student visa charge from 1 July 2026. Health cover is OSHC.'},ca:{cur:'C$',fund:23448,fee:235,note:'Study permit C$150 plus biometrics C$85. Ontario UHIP is C$948 for 2026-27.'},nz:{cur:'NZ$',fund:20000,fee:850,note:'Visa fee as reported. Confirm on the Immigration New Zealand fee page.'},ie:{cur:'€',fund:10000,fee:60,note:'Ireland also asks you to show at least €6,000 of tuition paid, or the full fee if lower.'}};
var HD={uk:776,au:600,ca:948,nz:0,ie:0};
var WI={
ielts:function(c){var v=['l','r','w','s'].map(function(k){return +g(c,k)}),t=+g(c,'t'),m=+g(c,'m'),avg=v.reduce(function(a,b){return a+b},0)/4,ov=Math.floor(avg*2+.5)/2;
var cefr=ov>=8.5?'C2':ov>=7?'C1':ov>=5.5?'B2':ov>=4?'B1':'A2 or below';
o(c,'res').textContent='Overall band '+ov.toFixed(1)+' (average '+avg.toFixed(3)+', about CEFR '+cefr+')';
var lows=['Listening','Reading','Writing','Speaking'].filter(function(n,i){return m&&v[i]<m});
var msg=[];msg.push(ov>=t?'You meet your overall target of '+t.toFixed(1)+'.':'You are '+(t-ov).toFixed(1)+' band'+((t-ov)>0.5?'s':'')+' below your overall target of '+t.toFixed(1)+'.');
if(m)msg.push(lows.length?'Below the '+m.toFixed(1)+' minimum: '+lows.join(', ')+'. Universities and visas that set a per-skill minimum check each section, so one weak section can fail you even with a good overall score.':'Every section meets the '+m.toFixed(1)+' minimum.');
if(ov<t){var need=Math.ceil(((t-0.25)*4-v.reduce(function(a,b){return a+b},0))*2)/2;msg.push('To reach '+t.toFixed(1)+' you would need roughly '+Math.max(0.5,need).toFixed(1)+' extra band points spread across the four sections. A One Skill Retake can lift a single weak section within 60 days of the original test.')}
o(c,'msg').textContent=msg.join(' ')},
plan:function(c){var dt=new Date(g(c,'d')),cc=g(c,'c'),now=new Date(),ms=[[12,'Shortlist and start documents','Choose 5 to 8 courses (safe, match, reach). Start HEC and IBCC attestation for your certificates and degrees.'],[11,'Book and take your English test','IELTS and most tests stay valid for 2 years, so take it early enough to retake if needed.'],[10,'Write your statement of purpose and brief referees','Give referees your CV and a one-page brief. Good references take weeks.'],[9,'Submit first applications and scholarship forms','Many scholarship deadlines fall 6 to 12 months before the intake.'],[7,'Offers arrive: compare and decide','Check conditions, fees, refund rules and scholarships in writing.'],[5,'Accept and pay the deposit','Request your CAS, CoE, I-20 or equivalent visa document. Pay only to the university account.'],[4,'Prepare funds and visa file','Match names and dates across passport, transcripts and bank papers.'],[3,'Lodge your visa application','Book biometrics, medical or TB tests if your country needs them.'],[2,'Sort accommodation, insurance and money transfer','Book first-night stay. Arrange tuition payment through an authorised dealer bank.'],[1,'Book flights, SIM and pack','Book after visa approval. Carry attested originals in hand luggage. Check your polio certificate.']];
var nt={uk:'UK: TB test for Pakistani applicants, 28-day funds rule, check whether your CAS needs an IELTS for UKVI test.',au:'Australia: prepare Genuine Student answers, buy OSHC, watch the national cap. Early offers matter.',ca:'Canada: confirm the provincial attestation rules and the cap for your programme before you pay a deposit.',us:'USA: book your F-1 interview slot as soon as you hold the I-20. Pay the SEVIS fee first.',nz:'New Zealand: medical and police certificates may be needed for courses longer than 12 months.',ie:'Ireland: check your course is on the eligible programmes list and pay at least €6,000 tuition.',my:'Malaysia: your university applies to EMGS for your eVAL. Processing is typically 4 to 8 weeks.',cn:'China: for CSC, watch the HEC portal in Nov to Jan. You need the JW201 or JW202 form and the physical examination record for the X1 visa.'};
var h='<ol class="tlv" style="margin-top:20px">'+ms.map(function(x,i){var d=new Date(dt);d.setMonth(d.getMonth()-x[0]);var past=d<now;return '<li data-n="'+(i+1)+'"><b>'+d.toLocaleDateString('en-GB',{month:'long',year:'numeric'})+': '+x[1]+(past?' <span class="bdg">already passed</span>':'')+'</b>'+x[2]+'</li>'}).join('')+'</ol>';
var months=(dt-now)/2629800000;h+='<div class="note">'+(months<9?'Your intake is only '+Math.max(0,Math.round(months))+' months away. Do steps 1 to 4 in parallel this month and ask counsellors which offers can be fast-tracked. ':'You have enough runway to do this in order. ')+nt[cc]+'</div>';o(c,'res').innerHTML=h},
funds:function(c){var k=g(c,'c'),d=FD[k],t=+g(c,'t')||0,hl=+g(c,'h')||0,r=+g(c,'r')||0,y=+g(c,'y')||1,lon=g(c,'lon')==='1';
o(c,'extra').style.display=k==='uk'?'':'none';
var fund=k==='uk'?(lon?d.per[1]:d.per[0])*9:d.fund,hh=k==='uk'?hl*y:hl,rows=[['Tuition (first year)',t],['Living-cost funds to show',fund],['Visa fees',d.fee],['Health cover'+(k==='uk'?' (surcharge for '+y+' yr)':''),hh]],tot=rows.reduce(function(a,b){return a+b[1]},0);
var buf=tot*.1;
var f=function(n){return d.cur+nf(n)+(r?'  (PKR '+nf(n*r)+')':'')};
o(c,'res').innerHTML='<div class="tw" style="margin-top:16px"><table><tbody>'+rows.map(function(x){return '<tr><td>'+x[0]+'</td><td>'+f(x[1])+'</td></tr>'}).join('')+'<tr><td><b>Minimum cash and tuition needed</b></td><td><b>'+f(tot)+'</b></td></tr><tr><td>Sensible 10% buffer for rate moves and first-month costs</td><td>'+f(buf)+'</td></tr><tr><td><b>Plan for</b></td><td><b>'+f(tot+buf)+'</b></td></tr></tbody></table></div><p class="src" style="margin-top:10px">'+d.note+' This shows visa and entry costs only. It excludes flights, deposits for housing and later-year tuition. Figures as checked on '+BZ.UPDATED+'.</p>'},
emi:function(c){var P=+g(c,'p')||0,i=(+g(c,'i')||0)/1200,n=(+g(c,'n')||1)*12,gm=+g(c,'g')||0,cap=g(c,'cap')==='1',fx=+g(c,'fx')||0;
var pr=cap?P*Math.pow(1+i,gm):P,em=i?pr*i*Math.pow(1+i,n)/(Math.pow(1+i,n)-1):pr/n,tot=em*n,dur=i*P;
var h='<div class="tw" style="margin-top:16px"><table><tbody><tr><td>Loan at start of repayment</td><td>PKR '+nf(pr)+'</td></tr>'+(cap?'':'<tr><td>Interest-only payment while studying</td><td>PKR '+nf(dur)+' per month</td></tr>')+'<tr><td><b>Monthly instalment</b></td><td><b>PKR '+nf(em)+'</b></td></tr><tr><td>Total repaid over '+(n/12)+' years</td><td>PKR '+nf(tot+(cap?0:dur*gm))+'</td></tr><tr><td>Total interest</td><td>PKR '+nf(tot+(cap?0:dur*gm)-P)+'</td></tr></tbody></table></div>';
if(fx)h+='<div class="note" style="margin-top:14px">Currency risk: if the rupee weakens '+fx+'% against the currency you spend, the foreign-currency part of your cost rises by the same share. If the whole loan is spent abroad, that is about PKR '+nf(P*fx/100)+' extra to find, on top of the figures above.</div>';o(c,'res').innerHTML=h},
pkr:function(c){var a=+g(c,'a')||0,r=+g(c,'r')||0,f=(+g(c,'f')||0)/100,x=+g(c,'x')||0;if(!r){o(c,'res').innerHTML='<p class="src">Enter the rate your bank quotes to see the rupee cost.</p>';return}var base=a*r,fee=base*f+x;o(c,'res').innerHTML='<div class="tw" style="margin-top:16px"><table><tbody><tr><td>Converted amount</td><td>PKR '+nf(base)+'</td></tr><tr><td>Bank charges</td><td>PKR '+nf(fee)+'</td></tr><tr><td><b>Total debit from your account</b></td><td><b>PKR '+nf(base+fee)+'</b></td></tr><tr><td>Effective rate you paid</td><td>PKR '+(a?((base+fee)/a).toFixed(2):'0')+' per unit</td></tr></tbody></table></div>'}};
function run(c){var t=c.getAttribute('data-wg');if(WI[t])WI[t](c)}
function initW(){document.querySelectorAll('[data-wg]').forEach(function(c){if(!c.dataset.on){c.dataset.on=1;if(c.dataset.wg==='funds'){var s=c.querySelector('[data-k="c"]');s.addEventListener('change',function(){var h=c.querySelector('[data-k="h"]');h.value=HD[s.value]})}}run(c)})}
document.addEventListener('input',function(e){var c=e.target.closest&&e.target.closest('[data-wg]');if(c)run(c)});
document.addEventListener('change',function(e){var c=e.target.closest&&e.target.closest('[data-wg]');if(c)run(c)});
document.addEventListener('click',function(e){var a=e.target.closest&&e.target.closest('[data-go]');if(a){e.preventDefault();var t=document.getElementById(a.getAttribute('data-go'));if(t)t.scrollIntoView({behavior:'smooth',block:'start'})}});
document.addEventListener('DOMContentLoaded',function(){var pg=document.getElementById('pg');if(pg)new MutationObserver(initW).observe(pg,{childList:true})});
/* ---------- renderer ---------- */
function blk(b,id){
if(typeof b==='string')return '<p>'+b+'</p>';
if(b.p)return '<p>'+b.p+'</p>';if(b.h3)return '<h3 class="sh">'+b.h3+'</h3>';if(b.ul)return L(b.ul);
if(b.ol)return '<ol class="tlv">'+b.ol.map(function(s,i){return '<li data-n="'+(i+1)+'"><b>'+s[0]+'</b>'+s[1]+'</li>'}).join('')+'</ol>';
if(b.table)return T(b.table.h,b.table.r,b.table.cap);
if(b.note)return '<div class="note">'+b.note+'</div>';
if(b.warn)return '<div class="note warn"><b>Watch out: </b>'+b.warn+'</div>';
if(b.cols)return '<div class="cols2">'+b.cols.map(function(c){return '<div class="card"><h3>'+c[0]+'</h3>'+L(c[1])+'</div>'}).join('')+'</div>';
if(b.cards)return '<div class="g3">'+b.cards.map(function(c){return '<div class="card"><h3>'+c[0]+'</h3><p>'+c[1]+'</p>'+(c[2]?'<a class="l" href="'+c[2]+'">'+(c[3]||'Read more')+'</a>':'')+'</div>'}).join('')+'</div>';
if(b.tags)return '<div class="tags">'+b.tags.map(function(t){return '<span>'+t+'</span>'}).join('')+'</div>';
if(b.acc)return '<div class="stp" style="max-width:860px">'+b.acc.map(function(q){return '<details><summary>'+q[0]+'</summary><p>'+q[1]+'</p></details>'}).join('')+'</div>';
if(b.chk)return '<ul class="chk">'+b.chk.map(function(x){return '<li>'+x+'</li>'}).join('')+'</ul>';
if(b.kv)return '<div class="kv">'+b.kv.map(function(k){return '<div><b>'+k[0]+'</b><span>'+k[1]+'</span></div>'}).join('')+'</div>';
if(b.w)return WG[b.w]();
if(b.kids)return '<div class="g3">'+(w.G[id]?w.G[id][1].map(w.cd).join(''):'')+'</div>';
if(b.src)return '<p class="src">'+b.src+'</p>';return ''}
function page(id,d){
var G=w.G,hubT=d.hub&&G[d.hub]?G[d.hub][0]:null;
var h='<div class="hero" style="padding:44px 0 '+(d.facts?90:56)+'px"><div class="w" style="grid-template-columns:1fr"><div><p style="font-size:13px;margin:0 0 14px"><a href="#/home" style="color:var(--navy)">BlueZone</a>'+(hubT?' / <a href="#/p/'+d.hub+'" style="color:var(--navy)">'+hubT+'</a>':'')+' / '+d.nav+'</p><h1 style="font-size:42px;max-width:840px">'+d.h+'</h1><p>'+d.lead+'</p><p class="upd">Last reviewed '+BZ.UPDATED+'. Figures are checked against the sources listed at the bottom of the page.</p><a class="btn" href="#/contact">Talk to a counsellor</a></div></div></div>';
if(d.facts)h+='<div class="w"><div class="facts">'+d.facts.map(function(f){return '<div class="fc"><b>'+f[0]+'</b><span>'+f[1]+'</span></div>'}).join('')+'</div></div>';
var secs=d.sec||[];
if(secs.length>3)h+='<div class="sub"><div class="w">'+secs.map(function(s){return '<a href="#/p/'+id+'" data-go="s-'+id+'-'+s.k+'">'+(s.s||s.t)+'</a>'}).join('')+(d.faq?'<a href="#/p/'+id+'" data-go="s-'+id+'-faq">FAQs</a>':'')+'</div></div>';
if(d.alert)h+='<section style="padding:26px 0 0"><div class="w"><div class="note alert">'+d.alert+'</div></div></section>';
secs.forEach(function(s,i){h+='<section id="s-'+id+'-'+s.k+'"'+(i%2?' class="alt"':'')+(i==0&&!d.alert&&d.facts?' style="padding-top:48px"':'')+'><div class="w"><h2>'+s.t+'</h2>'+(s.c||[]).map(function(b){return blk(b,id)}).join('')+'</div></section>'});
var n=secs.length;
if(d.faq)h+='<section id="s-'+id+'-faq"'+(n%2?' class="alt"':'')+'><div class="w"><h2>Frequently asked questions</h2>'+blk({acc:d.faq})+'</div></section>',n++;
if(d.src)h+='<section'+(n%2?' class="alt"':'')+'><div class="w"><h2>Sources and how we verify</h2><p class="src">Checked on '+BZ.UPDATED+'. This page is general information, not legal, immigration, medical or financial advice. Rules, fees and deadlines change, so confirm with the official body before you pay or apply.</p><ul class="src">'+d.src.map(function(s){return '<li><a href="'+s[1]+'" target="_blank" rel="noopener">'+s[0]+'</a></li>'}).join('')+'</ul></div></section>',n++;
h+='<section'+(n%2?' class="alt"':'')+'><div class="w"><div class="banner"><div><h3>'+(d.cta&&d.cta[0]||'Get a plan for your own profile')+'</h3><p>'+(d.cta&&d.cta[1]||'A BlueZone counsellor can check your grades, funds and documents before you apply or pay anything.')+'</p></div><a class="btn" href="#/contact">Book free counselling</a></div></div></section>';
var rel=d.rel||(d.hub&&G[d.hub]?G[d.hub][1].filter(function(x){return x!=id}).slice(0,3):[]);
if(rel.length)h+='<section'+((n+1)%2?' class="alt"':'')+'><div class="w"><h2>Keep going</h2><div class="g3">'+rel.map(w.cd).join('')+'</div></div></section>';
return h}
BZ.install=function(P,G,X){
Object.keys(BZ.add.P).forEach(function(k){P[k]=BZ.add.P[k]});
Object.keys(BZ.add.G).forEach(function(k){G[k][1]=BZ.add.G[k]});
Object.keys(BZ.pages).forEach(function(k){var d=BZ.pages[k];if(d.desc&&P[k])P[k][2]=d.desc;if(d.descG&&G[k])G[k][2]=d.descG});
Object.keys(BZ.pages).forEach(function(k){var d=BZ.pages[k];X[k]={h:page(k,d),t:d.t,f:d.faq,m:d.meta||d.lead,k:k}})};
/* ---------- structured data ---------- */
var BASE=(BZ.base||'');
BZ.ld=function(f,id){var old=document.getElementById('ldj');if(old)old.remove();var gph=[],X=w.X,x=X&&X[id],P=w.P,G=w.G,a=null;
var md=document.querySelector('meta[name="description"]');if(!BZ.md0&&md)BZ.md0=md.content;
if(id&&id.indexOf('blog/')==0){a=w.A.filter(function(z){return z.s==id.slice(5)})[0];if(a){if(md)md.content=a.x;gph.push({'@type':'Article','headline':a.t,'description':a.x,'datePublished':a.iso||BZ.ISO,'dateModified':a.iso||BZ.ISO,'articleSection':a.c,'author':{'@type':'Organization','name':'BlueZone Consultants'},'publisher':{'@type':'Organization','name':'BlueZone Consultants'}})}}
else if(x){if(md)md.content=x.m||BZ.md0;gph.push({'@type':'WebPage','name':x.t,'description':x.m,'dateModified':BZ.ISO,'inLanguage':'en','publisher':{'@type':'Organization','name':'BlueZone Consultants'}});
var q=P&&P[id],hub=q&&G&&G[q[1]];var items=[{'@type':'ListItem','position':1,'name':'BlueZone','item':BASE+'#/home'}];if(hub)items.push({'@type':'ListItem','position':2,'name':hub[0],'item':BASE+'#/p/'+q[1]});items.push({'@type':'ListItem','position':items.length+1,'name':x.t});gph.push({'@type':'BreadcrumbList','itemListElement':items})}
else if(md&&BZ.md0)md.content=BZ.md0;
if(f)gph.push({'@type':'FAQPage','mainEntity':f.map(function(z){return{'@type':'Question','name':z[0],'acceptedAnswer':{'@type':'Answer','text':z[1].replace(/<[^>]+>/g,'')}}})});
if(!gph.length)return;var s=document.createElement('script');s.id='ldj';s.type='application/ld+json';s.textContent=JSON.stringify({'@context':'https://schema.org','@graph':gph});document.head.appendChild(s)};
/* ---------- articles ---------- */
BZ.article=function(a,A){var body=a.b.map(function(p){if(typeof p==='object'){if(p.table)return T(p.table.h,p.table.r,p.table.cap);if(p.note)return '<div class="note">'+p.note+'</div>';if(p.ul)return L(p.ul);return ''}
if(p.indexOf('## ')==0)return '<h2 class="ah">'+p.slice(3)+'</h2>';return '<p class="b">'+p+'</p>'}).join('');
return '<a href="#/blog" style="color:var(--navy);font-weight:600">Back to all articles</a><h1>'+a.t+'</h1><div class="m">'+a.c+', '+a.d+', '+a.r+' read</div>'+body+(a.src?'<p class="src">Sources: '+a.src.map(function(s){return '<a href="'+s[1]+'" target="_blank" rel="noopener">'+s[0]+'</a>'}).join(', ')+'</p>':'')+'<div class="card"><h3>Want this applied to your own profile?</h3><p>A counsellor can review your documents and plan next steps with you.</p><a class="btn" href="#/contact">Book free counselling</a></div><h3>Keep reading</h3><div class="rel">'+A.filter(function(x){return x.s!=a.s}).slice(0,3).map(w.bcard).join('')+'</div>'};
})(window);
